Replace BlobStorage ConnectionString with Managed Identity
equinor/procosys-common pull request #44
Opened 2024-10-03 12:41 UTC by agustarnason

Updated BlobStorage to use Managed Identity instead of a ConnectionString

https://github.com/equinor/cc-toolbox/issues/527

2024-10-04 08:13 UTC, agustarnason commented
It could be possible that the part of the code that requires the AccountKey can be refactored away
I will do some digging and see what I can find

2024-10-09 07:53 UTC, janid1967 commented on src/Equinor.ProCoSys.BlobStorage/AzureBlobService.cs
> +        public string HostEndpoint { get; private set; }
as discussed
![image](https://github.com/user-attachments/assets/2c80bcd4-36ac-4a91-987c-7b28f54d271f)

2024-10-09 07:53 UTC, janid1967 approved these changes
approved after changing as discussed

2024-10-09 08:08 UTC, janid1967 approved these changes

2024-10-09 08:12 UTC, janid1967 requested changes
How should person who configure options.CurrentValue.BlobStorageAccountUrl know that the BlobStorageAccountUrl  should be just the host without https://????

2024-10-09 09:34 UTC, janid1967 approved these changes

2024-10-09 11:23 UTC, merged